version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: mathly
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
      - ./configuration/:/configuration/
    command: air
    image: cosmtrek/air:latest
    working_dir: /app
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 2s
      timeout: 2s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
    driver: local