// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -package common_games -destination=interfaces_mock.go
//

// Package common_games is a generated GoMock package.
package common_games

import (
	models "mathly/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGame is a mock of Game interface.
type MockGame struct {
	ctrl     *gomock.Controller
	recorder *MockGameMockRecorder
	isgomock struct{}
}

// MockGameMockRecorder is the mock recorder for MockGame.
type MockGameMockRecorder struct {
	mock *MockGame
}

// NewMockGame creates a new mock instance.
func NewMockGame(ctrl *gomock.Controller) *MockGame {
	mock := &MockGame{ctrl: ctrl}
	mock.recorder = &MockGameMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGame) EXPECT() *MockGameMockRecorder {
	return m.recorder
}

// GetRightAnswer mocks base method.
func (m *MockGame) GetRightAnswer(arg0 *int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRightAnswer", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRightAnswer indicates an expected call of GetRightAnswer.
func (mr *MockGameMockRecorder) GetRightAnswer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRightAnswer", reflect.TypeOf((*MockGame)(nil).GetRightAnswer), arg0)
}

// HandleMessage mocks base method.
func (m *MockGame) HandleMessage(arg0 models.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleMessage", arg0)
}

// HandleMessage indicates an expected call of HandleMessage.
func (mr *MockGameMockRecorder) HandleMessage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMessage", reflect.TypeOf((*MockGame)(nil).HandleMessage), arg0)
}

// StartTheGame mocks base method.
func (m *MockGame) StartTheGame() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartTheGame")
}

// StartTheGame indicates an expected call of StartTheGame.
func (mr *MockGameMockRecorder) StartTheGame() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTheGame", reflect.TypeOf((*MockGame)(nil).StartTheGame))
}
